using System.IO;
using System.Text;
using System.Text.Json;
using DeepSeekBrowser.Models;

namespace DeepSeekBrowser.Services.DeepSeekTui;

/// <summary>
/// 将桌面端设置同步到官方配置目录 <c>~/.deepseek/</c>（见 deepseek-tui.com/zh/docs）。
/// </summary>
public static class DeepSeekTuiConfigSync
{
    public static string HomeDirectory =>
        Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile), ".deepseek");

    public static string ConfigPath => Path.Combine(HomeDirectory, "config.toml");

    public static string McpPath => Path.Combine(HomeDirectory, "mcp.json");

    public static void Apply(AppConfig config)
    {
        Directory.CreateDirectory(HomeDirectory);
        Directory.CreateDirectory(Path.Combine(HomeDirectory, "skills"));

        WriteConfigToml(config);
        WriteMcpJson(config);
    }

    private static void WriteConfigToml(AppConfig config)
    {
        var snap = Chat2ApiProviderService.Build(config);
        var baseUrl = snap.Chat2ApiBaseUrl;
        var apiKey = snap.ApiKeyForClients;

        var defaultMode = string.Equals(config.DefaultAgentStrategy, AgentStrategies.Plan, StringComparison.OrdinalIgnoreCase)
            ? "plan"
            : "agent";

        var approval = MapApprovalMode(config.AgentApprovalMode);

        var sb = new StringBuilder();
        sb.AppendLine("# Generated by DeepSeek Desktop");
        sb.AppendLine("# 架构: 桌面端 → Runtime API (deepseek serve --http) → Engine/Tools/MCP (crates/tui)");
        sb.AppendLine("# LLM: 仅经本地 Chat2API（网页 User Token），见 https://github.com/Hmbown/DeepSeek-TUI/blob/main/docs/ARCHITECTURE.md");
        sb.AppendLine($"# Chat2API: {baseUrl}");
        sb.AppendLine();
        sb.AppendLine($"api_key = \"{EscapeToml(apiKey)}\"");
        sb.AppendLine($"base_url = \"{EscapeToml(baseUrl)}\"");
        sb.AppendLine("default_text_model = \"deepseek-v4-pro\"");
        sb.AppendLine();
        sb.AppendLine("[runtime_api]");
        sb.AppendLine("cors_origins = [\"https://ds-agent.local\"]");
        sb.AppendLine();
        sb.AppendLine("[ui]");
        sb.AppendLine($"default_mode = \"{defaultMode}\"");
        sb.AppendLine($"approval_mode = \"{approval}\"");
        sb.AppendLine("reasoning_effort = \"high\"");

        File.WriteAllText(ConfigPath, sb.ToString(), Encoding.UTF8);
    }

    private static string MapApprovalMode(string? mode) => mode?.ToLowerInvariant() switch
    {
        "never" => "auto",
        "always" => "suggest",
        "readonly" => "suggest",
        _ => "suggest",
    };

    private static void WriteMcpJson(AppConfig config)
    {
        var servers = new Dictionary<string, object>();
        foreach (var s in config.McpServers.Where(x => x.Enabled))
        {
            var id = string.IsNullOrWhiteSpace(s.Id) ? Guid.NewGuid().ToString("N")[..8] : s.Id;
            if (s.IsRemote && !string.IsNullOrWhiteSpace(s.Url))
            {
                servers[id] = new Dictionary<string, object?>
                {
                    ["url"] = s.Url,
                    ["transport"] = "http"
                };
            }
            else
            {
                servers[id] = new Dictionary<string, object?>
                {
                    ["command"] = s.Command,
                    ["args"] = s.Arguments.ToArray(),
                };
                if (!string.IsNullOrWhiteSpace(s.WorkingDirectory))
                    ((Dictionary<string, object?>)servers[id])["cwd"] = s.WorkingDirectory;
            }
        }

        var root = new Dictionary<string, object> { ["mcpServers"] = servers };
        var json = JsonSerializer.Serialize(root, new JsonSerializerOptions { WriteIndented = true });
        File.WriteAllText(McpPath, json, Encoding.UTF8);
    }

    private static string EscapeToml(string value) =>
        value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
